---
include:
    # - board: nice_nano_v2
    #   shield: catostyl_dongle dongle_display
    - board: nice_nano_v2
      shield: catostyl_dongle
    - board: nice_nano_v2
      shield: catostyl_left
    - board: nice_nano_v2
      shield: catostyl_right
    # - board: nice_nano_v2
    #   shield: settings_reset
