---
include:
    - board: nice_nano_v2
      shield: catostyl_dongle dongle_display
      artifact-name: catostyl_dongle
    - board: nice_nano_v2
      shield: catostyl_left
      artifact-name: catostyl_left
    - board: nice_nano_v2
      shield: catostyl_right
      artifact-name: catostyl_right
    # - board: nice_nano_v2
    #   shield: settings_reset
