file_format: '1'
id: catostyl
name: Catostyl
type: shield
url: https://github.com/9u0vad15/catostyl
requires: [nice_nano_v2]
features:
    - keys
siblings:
    - catostyl_center
    - catostyl_left
    - catostyl_right
